version: "3.8"
services:
  node:
    image: node:14.17.0
    container_name: node
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: sh -c "npm install && npm run generate-dist && chmod -R 775 ./dist && chown -R www-data:www-data"